services:
  app:
    image: ghcr.io/fairchildovo/infinite-canvas:latest
    container_name: infinite-canvas
    env_file:
      - .env
    environment:
      HTTP_PROXY: http://host.docker.internal:7890
      HTTPS_PROXY: http://host.docker.internal:7890
      NO_PROXY: 127.0.0.1,localhost
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped
